#!/bin/sh

awk "/#@${1}@#/, /#@END${1}@#/ {
       if ( first == 0 ) {
         print(\"#@${1}@#\");
         system(\"cat $3\");
         print(\"#@END${1}@#\");
         first=1;
       }
       next;
     }

     {
       print \$0;
     }" $2

